name: Register your intrest and a bit about you
description: Use your full name as the title.
body:
  - type: dropdown
    id: notification
    attributes:
      label: Notifications in GitHub setup
      description: |
        We assume that you have setup [notifications on your GitHub account](https://github.com/notifications) in such a a way, that we can communicate with you through _mentions_ and _assignments_ on issues - is that a fair assumption?
      options:
        - Yep - that's right, hit me!
        - No - I don't know how to set that up
      default: 0
    validations:
      required: true
      
  - type: dropdown
    id: education
    attributes:
      label: Relevant education
      description: Please indicate the education level you're currently studying
      options:
        - I'm currently studying a relevant master degree
        - I'm currently studying a relevant bachelor degree
        - I'm currently studying something else.
      default: 0
    validations:
      required: true

  - type: textarea
    id: programme
    attributes:
      label: Your study
      description: |
        Describe the school and study programme you are attending, how far are you in your study, how long is your intersnhip period, when 
        does it start, are there any special requirements you must fulfill towards your study for this internship.
      placeholder: |
        I'm styding at ...
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |        
        Go through this series of checkboxes below and check everyone where you have some experience.
  - type: checkboxes
    id: os
    attributes:
      description: Check all that applies.
      label: Which operating systems and OS technologies have you used?
      options:
        - label: Windows
        - label: MacOS
        - label: Linux    
    validations:
      required: false

  - type: checkboxes
    id: languages
    attributes:
      description: Check all that applies 
      label: Which programming languages and dtabase technologies have you used?
      options:
        - label: JavaScript or TypeScript
        - label: Java 
        - label: C# and .NET (core included)
        - label: Python
        - label: Go 
        - label: Rust or Dart
        - label: C or C++
        - label: Relational databases
        - label: Document (no-sal) databases
        - label: ...other
    validations:
      required: false

  - type: checkboxes
    id: clouds
    attributes:
      description: Check all that applies
      label: Which clouds, platforms or frameworks have you used?
      options:
        - label: AWS
        - label: GCP
        - label: Azure
        - label: Kubernetes
        - label: Firebase or Supabase
        - label: Flutter or React Native
        - label: ...other
    validations:
      required: false
