name: Register your intrest and a bit about you
description: Use your full name as the title.
body:
  - type: dropdown
    id: notification
    attributes:
      label: Notifications in GitHub setup
      description: |
        We assume that you have setup [notifications on your GitHub account](https://github.com/notifications) in such a a way, that we can communicate with you through _mentions_ and _assignments_ on issues - is that a fair assumption?
      options:
        - Yep - that's right, hit me!
        - No - I don't know how to set that up
      default: 0
    validations:
      required: true
      
  - type: dropdown
    id: education
    attributes:
      label: Relevant education
      description: Please indicate the education level you're currently studying
      options:
        - I'm currently studying a relevant master degree
        - I'm currently studying a relevant bachelor degree
        - I'm currently studying something else.
      default: 0
    validations:
      required: true

  - type: textarea
    id: programme
    attributes:
      label: Your study
      description: |
        Describe the school and study programme you are attending, how far are you in your study, how long is your intersnhip period, when 
        does it start, are there any special requirements you must fulfill towards your study for this internship.
      placeholder: |
        I'm styding at ...
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |        
        Go through this series of checkboxes below and check everyone where you have some experience.
  - type: checkboxes
    id: os
    attributes:
      description: Check all that applies.
      label: Which operating systems and OS technologies have you used?
      options:
        - label: Windows
        - label: MacOS
        - label: Linux    
    validations:
      required: false

  - type: checkboxes
    id: languages
    attributes:
      description: Check all that applies 
      label: Which programming languages and dtabase technologies have you used?
      options:
        - label: JavaScript or TypeScript
        - label: Java 
        - label: C# and .NET (core included)
        - label: Python
        - label: Go 
        - label: Rust or Dart
        - label: C or C++
        - label: Relational databases
        - label: Document (no-sal) databases
        - label: ...other
    validations:
      required: false

  - type: checkboxes
    id: clouds
    attributes:
      description: Check all that applies
      label: Which clouds, platforms or frameworks have you used?
      options:
        - label: AWS
        - label: GCP
        - label: Azure
        - label: Kubernetes
        - label: Firebase or Supabase
        - label: Flutter or React Native
        - label: ...other
    validations:
      required: false
      
  - type: checkboxes
    id: testtools
    attributes:
      description: Check all that applies
      label: Which test technologies, tools and approaches have you _automated?_
      options:
        - label: Unit tests
        - label: Static Code Analysis
        - label: Integration tests
        - label: End-to-end tests / Functional tests
        - label: Performance/Load tests
        - label: ...other 
    validations:
      required: false

  - type: textarea
    id: tech
    attributes:
      label: Other tech you fancy
      description: |
        Describe any other technology or languages you've used
      placeholder: |
        I also know...
    validations:
      required: false
 

 
  - type: textarea
    id: in-your-own-words
    attributes:
      label: In your own words...
      description: |
        Use a few sentences to describe yourself; the study programme and school you are attending, from a perspective of _DevOps_ 
        and _Software Development_ list some of the things that you find interesting and would like to develop your skills.
      placeholder: |
        I wanna become good at...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        🤷‍♂️ Maybe you had more information you wanted to get off your chest?
        
        > [!TIP]
        > When you have submitted this issue, you can go back and find and open it and then chose to _edit_ the description.
        > It will open up as raw MarkDown - and you can take it in any direction you want - knock yourself out!
