blank_issues_enabled: false
contact_links:
  - name: Do you need to start a conversation or ask a question? 
    url: https://github.com/orgs/tt-internship/discussions/
    about: The link takes you to our public discussion on our .tech that Internshipå community.  
